version: "3.9"

services:
  backend:
    build:
      context: ./expense-tracker-api
      dockerfile: Dockerfile
    container_name: budget-backend
    env_file:
      - .env
    volumes:
      - ./expense-tracker-api:/app
      - ./certs:/app/certs
      - /app/node_modules
    ports:
      - "3001:3001"
    command: npm run dev
    restart: unless-stopped

  frontend:
    build:
      context: ./expense-tracker-frontend
      dockerfile: Dockerfile
    container_name: budget-frontend
    volumes:
      - ./expense-tracker-frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
    - CHOKIDAR_USEPOLLING=true
    - HOST=0.0.0.0
    depends_on:
      - backend
    restart: unless-stopped
