name: Budget Tracker CI/CD

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ main ]

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        
      - name: Install API Dependencies
        run: npm install
        working-directory: ./expense-tracker-api
      
      - name: Generate Prisma Client
        run: npx prisma generate
        working-directory: ./expense-tracker-api

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Frontend Dependencies
        run: npm install
        working-directory: ./expense-tracker-frontend

      - name: Build Frontend
        run: npm run build
        working-directory: ./expense-tracker-frontend

  build-and-push-images:
    needs: [build-api, build-frontend]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lowercase repository name
        run: |
          echo "REPO_LOWER=${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push API Image
        uses: docker/build-push-action@v5
        with:
          context: ./expense-tracker-api
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LOWER }}/api:${{ github.sha }}
            ghcr.io/${{ env.REPO_LOWER }}/api:latest
      
      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./expense-tracker-frontend
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LOWER }}/frontend:${{ github.sha }}
            ghcr.io/${{ env.REPO_LOWER }}/frontend:latest